repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - --recursive
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
          - --exclude
          - __init__.py
          - --remove-duplicate-keys
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
        name: isort (python)
  - repo: https://github.com/pycqa/pylint
    rev: v2.10.2
    hooks:
      - id: pylint
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: local
    hooks:
      - id: tests
        name: run tests
        entry: pytest -v
        language: system
        types: [python]
        stages: [push]
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
